/* tslint:disable */
/* eslint-disable */
/**
 * Account Docs
 * Account endpoints...
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AccountInfo {
    'id': string;
    'firstName': string;
    'lastName': string;
    'phone': string;
    'email': string;
    'state': string;
    'stateArea': string;
    'profilePhoto': string;
    'accountType': AccountInfoAccountTypeEnum;
    'status': AccountInfoStatusEnum;
    'fcmToken': string;
    'referralCode': string;
    'xHandle': string;
    'instagramHandle': string;
    'tiktokHandle': string;
    'snapchatHandle': string;
}

export const AccountInfoAccountTypeEnum = {
    Individual: 'individual',
    Admin: 'admin',
    SuperAdmin: 'super_admin',
    System: 'system'
} as const;

export type AccountInfoAccountTypeEnum = typeof AccountInfoAccountTypeEnum[keyof typeof AccountInfoAccountTypeEnum];
export const AccountInfoStatusEnum = {
    Pending: 'pending',
    Active: 'active',
    Inactive: 'inactive',
    ShadowBanned: 'shadow_banned',
    Disabled: 'disabled'
} as const;

export type AccountInfoStatusEnum = typeof AccountInfoStatusEnum[keyof typeof AccountInfoStatusEnum];

export interface ContactUsDTO {
    /**
     * The name of the user
     */
    'name': string;
    /**
     * The email of the user
     */
    'email': string;
    /**
     * The subject of the message
     */
    'subject': string;
    /**
     * The message from the user
     */
    'message': string;
}
export interface DeleteAccountDTO {
    /**
     * Current account password.
     */
    'password': string;
}
export interface FileUploadResult {
    'url': string;
    'public_id': string;
}
export interface MonthlySurveyHistoryResponse {
    /**
     * Monthly survey history.
     */
    'surveys': Array<MonthlySurveyInfo>;
    /**
     * Total number of pages.
     */
    'totalPages': number;
    /**
     * Has next page.
     */
    'hasNext': boolean;
}
export interface MonthlySurveyInfo {
    /**
     * Monthly survey ID (Auto generated).
     */
    'id': string;
    /**
     * Monthly survey days managing period.
     */
    'daysManagingPeriod': string;
    /**
     * Monthly survey challengesFaced.
     */
    'challengesFaced': Array<string>;
    /**
     * Monthly survey hasAccessToPad.
     */
    'hasAccessToPad': boolean;
}
export interface NotificationInfo {
    'id': string;
    'title': string;
    'message': string;
    'isRead': boolean;
    'createdAt': string;
    'product'?: NotificationProductInfo;
}
export interface NotificationProductInfo {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'price'?: string;
}
export interface NotificationsResponse {
    'notifications': Array<NotificationInfo>;
    'totalPages': number;
    'hasNextPage': boolean;
}
export interface OrderHistoryResponse {
    /**
     * Order history.
     */
    'orders': Array<OrderInfo>;
    /**
     * Total number of pages.
     */
    'totalPages': number;
    /**
     * Has next page.
     */
    'hasNext': boolean;
}
export interface OrderInfo {
    /**
     * Order ID (Auto generated).
     */
    'id': string;
    /**
     * Order ID (Custom generated).
     */
    'orderId': string;
    /**
     * Order quantity e.g 1
     */
    'quantity': number;
    /**
     * Order delivery method e.g PickUp.
     */
    'deliveryMethod': OrderInfoDeliveryMethodEnum;
    /**
     * Order completed status e.g false.
     */
    'isCompleted': boolean;
    /**
     * Order building number e.g 123.
     */
    'buildingNumber': string;
    /**
     * Order address e.g 123 Main St, Anytown, USA.
     */
    'address': string;
    /**
     * Order nearest landmark e.g 123 Main St, Anytown, USA.
     */
    'nearestLandmark': string;
}

export const OrderInfoDeliveryMethodEnum = {
    Delivery: 'Delivery',
    Pickup: 'Pickup'
} as const;

export type OrderInfoDeliveryMethodEnum = typeof OrderInfoDeliveryMethodEnum[keyof typeof OrderInfoDeliveryMethodEnum];

export interface OrderSanitaryPadDTO {
    /**
     * Quantity
     */
    'quantity': number;
    /**
     * Delivery method.
     */
    'deliveryMethod': string;
    /**
     * Building number.
     */
    'buildingNumber': string;
    /**
     * Address.
     */
    'address': string;
    /**
     * Nearest landmark.
     */
    'nearestLandmark': string;
}
export interface RegisterMonthlySurveyDTO {
    'hasAccessToPad': boolean;
    'daysManagingMenstruation': RegisterMonthlySurveyDTODaysManagingMenstruationEnum;
    'challengesFaced': string;
}

export const RegisterMonthlySurveyDTODaysManagingMenstruationEnum = {
    None: 'None',
    OneToThreeDays: 'OneToThreeDays',
    FourToFiveDays: 'FourToFiveDays',
    MoreThanFiveDays: 'MoreThanFiveDays'
} as const;

export type RegisterMonthlySurveyDTODaysManagingMenstruationEnum = typeof RegisterMonthlySurveyDTODaysManagingMenstruationEnum[keyof typeof RegisterMonthlySurveyDTODaysManagingMenstruationEnum];

export interface UpdateAccountEmailDTO {
    /**
     * New account email.
     */
    'newEmail': string;
}
export interface UpdateAccountLocationDTO {
    /**
     * User state.
     */
    'state': string;
    /**
     * User city.
     */
    'city': string;
}
export interface UpdateAccountNameDTO {
    /**
     * New account first name.
     */
    'firstName': string;
    /**
     * New account last name.
     */
    'lastName': string;
}
export interface UpdateAccountPasswordDTO {
    /**
     * Current account password.
     */
    'currentPassword': string;
    /**
     * New account password.
     */
    'newPassword': string;
}
export interface UpdateAccountPhoneDTO {
    /**
     * New account phone.
     */
    'newPhone': string;
    /**
     * Account password.
     */
    'password': string;
}
export interface UpdateFCMTokenDTO {
    /**
     * FCM token for push notifications generated by mobile device.
     */
    'fcmToken': string;
}
export interface UpdateProfileImageDTO {
    /**
     * URL of the image to be uploaded.
     */
    'imageUrl': string;
}
export interface UpdateSocialHandlesDTO {
    'xHandle': string;
    'instagramHandle': string;
    'tiktokHandle': string;
    'snapchatHandle': string;
}
export interface VerifyNewAccountEmailDTO {
    /**
     * Activation token (OTP)
     */
    'otp': string;
}

/**
 * ManageContactInfoApi - axios parameter creator
 */
export const ManageContactInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UpdateAccountEmailDTO} updateAccountEmailDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountEmail: async (updateAccountEmailDTO: UpdateAccountEmailDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateAccountEmailDTO' is not null or undefined
            assertParamExists('accountControllerUpdateAccountEmail', 'updateAccountEmailDTO', updateAccountEmailDTO)
            const localVarPath = `/v1/account/me/update-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAccountEmailDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateAccountLocationDTO} updateAccountLocationDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountLocation: async (updateAccountLocationDTO: UpdateAccountLocationDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateAccountLocationDTO' is not null or undefined
            assertParamExists('accountControllerUpdateAccountLocation', 'updateAccountLocationDTO', updateAccountLocationDTO)
            const localVarPath = `/v1/account/me/update-location`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAccountLocationDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateAccountNameDTO} updateAccountNameDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountName: async (updateAccountNameDTO: UpdateAccountNameDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateAccountNameDTO' is not null or undefined
            assertParamExists('accountControllerUpdateAccountName', 'updateAccountNameDTO', updateAccountNameDTO)
            const localVarPath = `/v1/account/me/update-name`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAccountNameDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateAccountPhoneDTO} updateAccountPhoneDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountPhone: async (updateAccountPhoneDTO: UpdateAccountPhoneDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateAccountPhoneDTO' is not null or undefined
            assertParamExists('accountControllerUpdateAccountPhone', 'updateAccountPhoneDTO', updateAccountPhoneDTO)
            const localVarPath = `/v1/account/me/update-phone`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAccountPhoneDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VerifyNewAccountEmailDTO} verifyNewAccountEmailDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerVerifyNewAccountEmail: async (verifyNewAccountEmailDTO: VerifyNewAccountEmailDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verifyNewAccountEmailDTO' is not null or undefined
            assertParamExists('accountControllerVerifyNewAccountEmail', 'verifyNewAccountEmailDTO', verifyNewAccountEmailDTO)
            const localVarPath = `/v1/account/me/verify-new-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyNewAccountEmailDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ManageContactInfoApi - functional programming interface
 */
export const ManageContactInfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ManageContactInfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {UpdateAccountEmailDTO} updateAccountEmailDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerUpdateAccountEmail(updateAccountEmailDTO: UpdateAccountEmailDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerUpdateAccountEmail(updateAccountEmailDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ManageContactInfoApi.accountControllerUpdateAccountEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateAccountLocationDTO} updateAccountLocationDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerUpdateAccountLocation(updateAccountLocationDTO: UpdateAccountLocationDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerUpdateAccountLocation(updateAccountLocationDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ManageContactInfoApi.accountControllerUpdateAccountLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateAccountNameDTO} updateAccountNameDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerUpdateAccountName(updateAccountNameDTO: UpdateAccountNameDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerUpdateAccountName(updateAccountNameDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ManageContactInfoApi.accountControllerUpdateAccountName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateAccountPhoneDTO} updateAccountPhoneDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerUpdateAccountPhone(updateAccountPhoneDTO: UpdateAccountPhoneDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerUpdateAccountPhone(updateAccountPhoneDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ManageContactInfoApi.accountControllerUpdateAccountPhone']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {VerifyNewAccountEmailDTO} verifyNewAccountEmailDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerVerifyNewAccountEmail(verifyNewAccountEmailDTO: VerifyNewAccountEmailDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerVerifyNewAccountEmail(verifyNewAccountEmailDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ManageContactInfoApi.accountControllerVerifyNewAccountEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ManageContactInfoApi - factory interface
 */
export const ManageContactInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ManageContactInfoApiFp(configuration)
    return {
        /**
         * 
         * @param {UpdateAccountEmailDTO} updateAccountEmailDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountEmail(updateAccountEmailDTO: UpdateAccountEmailDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerUpdateAccountEmail(updateAccountEmailDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateAccountLocationDTO} updateAccountLocationDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountLocation(updateAccountLocationDTO: UpdateAccountLocationDTO, options?: RawAxiosRequestConfig): AxiosPromise<AccountInfo> {
            return localVarFp.accountControllerUpdateAccountLocation(updateAccountLocationDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateAccountNameDTO} updateAccountNameDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountName(updateAccountNameDTO: UpdateAccountNameDTO, options?: RawAxiosRequestConfig): AxiosPromise<AccountInfo> {
            return localVarFp.accountControllerUpdateAccountName(updateAccountNameDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateAccountPhoneDTO} updateAccountPhoneDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountPhone(updateAccountPhoneDTO: UpdateAccountPhoneDTO, options?: RawAxiosRequestConfig): AxiosPromise<AccountInfo> {
            return localVarFp.accountControllerUpdateAccountPhone(updateAccountPhoneDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VerifyNewAccountEmailDTO} verifyNewAccountEmailDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerVerifyNewAccountEmail(verifyNewAccountEmailDTO: VerifyNewAccountEmailDTO, options?: RawAxiosRequestConfig): AxiosPromise<AccountInfo> {
            return localVarFp.accountControllerVerifyNewAccountEmail(verifyNewAccountEmailDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ManageContactInfoApi - object-oriented interface
 */
export class ManageContactInfoApi extends BaseAPI {
    /**
     * 
     * @param {UpdateAccountEmailDTO} updateAccountEmailDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerUpdateAccountEmail(updateAccountEmailDTO: UpdateAccountEmailDTO, options?: RawAxiosRequestConfig) {
        return ManageContactInfoApiFp(this.configuration).accountControllerUpdateAccountEmail(updateAccountEmailDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateAccountLocationDTO} updateAccountLocationDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerUpdateAccountLocation(updateAccountLocationDTO: UpdateAccountLocationDTO, options?: RawAxiosRequestConfig) {
        return ManageContactInfoApiFp(this.configuration).accountControllerUpdateAccountLocation(updateAccountLocationDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateAccountNameDTO} updateAccountNameDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerUpdateAccountName(updateAccountNameDTO: UpdateAccountNameDTO, options?: RawAxiosRequestConfig) {
        return ManageContactInfoApiFp(this.configuration).accountControllerUpdateAccountName(updateAccountNameDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateAccountPhoneDTO} updateAccountPhoneDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerUpdateAccountPhone(updateAccountPhoneDTO: UpdateAccountPhoneDTO, options?: RawAxiosRequestConfig) {
        return ManageContactInfoApiFp(this.configuration).accountControllerUpdateAccountPhone(updateAccountPhoneDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {VerifyNewAccountEmailDTO} verifyNewAccountEmailDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerVerifyNewAccountEmail(verifyNewAccountEmailDTO: VerifyNewAccountEmailDTO, options?: RawAxiosRequestConfig) {
        return ManageContactInfoApiFp(this.configuration).accountControllerVerifyNewAccountEmail(verifyNewAccountEmailDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MeApi - axios parameter creator
 */
export const MeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {DeleteAccountDTO} deleteAccountDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerDeleteAccount: async (deleteAccountDTO: DeleteAccountDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteAccountDTO' is not null or undefined
            assertParamExists('accountControllerDeleteAccount', 'deleteAccountDTO', deleteAccountDTO)
            const localVarPath = `/v1/account/me/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteAccountDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerGetDetailedAccountInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/account/me/detailed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateAccountPasswordDTO} updateAccountPasswordDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountPassword: async (updateAccountPasswordDTO: UpdateAccountPasswordDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateAccountPasswordDTO' is not null or undefined
            assertParamExists('accountControllerUpdateAccountPassword', 'updateAccountPasswordDTO', updateAccountPasswordDTO)
            const localVarPath = `/v1/account/me/update-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAccountPasswordDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateFCMTokenDTO} updateFCMTokenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateFcmToken: async (updateFCMTokenDTO: UpdateFCMTokenDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateFCMTokenDTO' is not null or undefined
            assertParamExists('accountControllerUpdateFcmToken', 'updateFCMTokenDTO', updateFCMTokenDTO)
            const localVarPath = `/v1/account/me/update-fcm-token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateFCMTokenDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateProfileImageDTO} updateProfileImageDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateProfileImage: async (updateProfileImageDTO: UpdateProfileImageDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateProfileImageDTO' is not null or undefined
            assertParamExists('accountControllerUpdateProfileImage', 'updateProfileImageDTO', updateProfileImageDTO)
            const localVarPath = `/v1/account/me/update-profile-image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateProfileImageDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeApi - functional programming interface
 */
export const MeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {DeleteAccountDTO} deleteAccountDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerDeleteAccount(deleteAccountDTO: DeleteAccountDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerDeleteAccount(deleteAccountDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeApi.accountControllerDeleteAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerGetDetailedAccountInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerGetDetailedAccountInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeApi.accountControllerGetDetailedAccountInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateAccountPasswordDTO} updateAccountPasswordDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerUpdateAccountPassword(updateAccountPasswordDTO: UpdateAccountPasswordDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerUpdateAccountPassword(updateAccountPasswordDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeApi.accountControllerUpdateAccountPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateFCMTokenDTO} updateFCMTokenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerUpdateFcmToken(updateFCMTokenDTO: UpdateFCMTokenDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerUpdateFcmToken(updateFCMTokenDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeApi.accountControllerUpdateFcmToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateProfileImageDTO} updateProfileImageDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerUpdateProfileImage(updateProfileImageDTO: UpdateProfileImageDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerUpdateProfileImage(updateProfileImageDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeApi.accountControllerUpdateProfileImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MeApi - factory interface
 */
export const MeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MeApiFp(configuration)
    return {
        /**
         * 
         * @param {DeleteAccountDTO} deleteAccountDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerDeleteAccount(deleteAccountDTO: DeleteAccountDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerDeleteAccount(deleteAccountDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerGetDetailedAccountInfo(options?: RawAxiosRequestConfig): AxiosPromise<AccountInfo> {
            return localVarFp.accountControllerGetDetailedAccountInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateAccountPasswordDTO} updateAccountPasswordDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateAccountPassword(updateAccountPasswordDTO: UpdateAccountPasswordDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerUpdateAccountPassword(updateAccountPasswordDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateFCMTokenDTO} updateFCMTokenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateFcmToken(updateFCMTokenDTO: UpdateFCMTokenDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.accountControllerUpdateFcmToken(updateFCMTokenDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateProfileImageDTO} updateProfileImageDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateProfileImage(updateProfileImageDTO: UpdateProfileImageDTO, options?: RawAxiosRequestConfig): AxiosPromise<AccountInfo> {
            return localVarFp.accountControllerUpdateProfileImage(updateProfileImageDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeApi - object-oriented interface
 */
export class MeApi extends BaseAPI {
    /**
     * 
     * @param {DeleteAccountDTO} deleteAccountDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerDeleteAccount(deleteAccountDTO: DeleteAccountDTO, options?: RawAxiosRequestConfig) {
        return MeApiFp(this.configuration).accountControllerDeleteAccount(deleteAccountDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerGetDetailedAccountInfo(options?: RawAxiosRequestConfig) {
        return MeApiFp(this.configuration).accountControllerGetDetailedAccountInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateAccountPasswordDTO} updateAccountPasswordDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerUpdateAccountPassword(updateAccountPasswordDTO: UpdateAccountPasswordDTO, options?: RawAxiosRequestConfig) {
        return MeApiFp(this.configuration).accountControllerUpdateAccountPassword(updateAccountPasswordDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateFCMTokenDTO} updateFCMTokenDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerUpdateFcmToken(updateFCMTokenDTO: UpdateFCMTokenDTO, options?: RawAxiosRequestConfig) {
        return MeApiFp(this.configuration).accountControllerUpdateFcmToken(updateFCMTokenDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateProfileImageDTO} updateProfileImageDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerUpdateProfileImage(updateProfileImageDTO: UpdateProfileImageDTO, options?: RawAxiosRequestConfig) {
        return MeApiFp(this.configuration).accountControllerUpdateProfileImage(updateProfileImageDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MonthlySurveyApi - axios parameter creator
 */
export const MonthlySurveyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} page Page
         * @param {number} pageSize Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerFetchMonthlySurveyHistory: async (page: number, pageSize: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            assertParamExists('accountControllerFetchMonthlySurveyHistory', 'page', page)
            // verify required parameter 'pageSize' is not null or undefined
            assertParamExists('accountControllerFetchMonthlySurveyHistory', 'pageSize', pageSize)
            const localVarPath = `/v1/account/me/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RegisterMonthlySurveyDTO} registerMonthlySurveyDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerRegisterMonthlySurvey: async (registerMonthlySurveyDTO: RegisterMonthlySurveyDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerMonthlySurveyDTO' is not null or undefined
            assertParamExists('accountControllerRegisterMonthlySurvey', 'registerMonthlySurveyDTO', registerMonthlySurveyDTO)
            const localVarPath = `/v1/account/me/new`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerMonthlySurveyDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MonthlySurveyApi - functional programming interface
 */
export const MonthlySurveyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MonthlySurveyApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} page Page
         * @param {number} pageSize Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerFetchMonthlySurveyHistory(page: number, pageSize: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MonthlySurveyHistoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerFetchMonthlySurveyHistory(page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MonthlySurveyApi.accountControllerFetchMonthlySurveyHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RegisterMonthlySurveyDTO} registerMonthlySurveyDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerRegisterMonthlySurvey(registerMonthlySurveyDTO: RegisterMonthlySurveyDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MonthlySurveyInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerRegisterMonthlySurvey(registerMonthlySurveyDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MonthlySurveyApi.accountControllerRegisterMonthlySurvey']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MonthlySurveyApi - factory interface
 */
export const MonthlySurveyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MonthlySurveyApiFp(configuration)
    return {
        /**
         * 
         * @param {number} page Page
         * @param {number} pageSize Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerFetchMonthlySurveyHistory(page: number, pageSize: number, options?: RawAxiosRequestConfig): AxiosPromise<MonthlySurveyHistoryResponse> {
            return localVarFp.accountControllerFetchMonthlySurveyHistory(page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RegisterMonthlySurveyDTO} registerMonthlySurveyDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerRegisterMonthlySurvey(registerMonthlySurveyDTO: RegisterMonthlySurveyDTO, options?: RawAxiosRequestConfig): AxiosPromise<MonthlySurveyInfo> {
            return localVarFp.accountControllerRegisterMonthlySurvey(registerMonthlySurveyDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MonthlySurveyApi - object-oriented interface
 */
export class MonthlySurveyApi extends BaseAPI {
    /**
     * 
     * @param {number} page Page
     * @param {number} pageSize Page size
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerFetchMonthlySurveyHistory(page: number, pageSize: number, options?: RawAxiosRequestConfig) {
        return MonthlySurveyApiFp(this.configuration).accountControllerFetchMonthlySurveyHistory(page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RegisterMonthlySurveyDTO} registerMonthlySurveyDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerRegisterMonthlySurvey(registerMonthlySurveyDTO: RegisterMonthlySurveyDTO, options?: RawAxiosRequestConfig) {
        return MonthlySurveyApiFp(this.configuration).accountControllerRegisterMonthlySurvey(registerMonthlySurveyDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * NotificationsApi - axios parameter creator
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountNotificationControllerGetNotifications: async (page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/account/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [notificationId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountNotificationControllerReadNotification: async (notificationId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/account/notifications/read`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (notificationId !== undefined) {
                localVarQueryParameter['notificationId'] = notificationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationsApi - functional programming interface
 */
export const NotificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountNotificationControllerGetNotifications(page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountNotificationControllerGetNotifications(page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.accountNotificationControllerGetNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [notificationId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountNotificationControllerReadNotification(notificationId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountNotificationControllerReadNotification(notificationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.accountNotificationControllerReadNotification']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationsApi - factory interface
 */
export const NotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationsApiFp(configuration)
    return {
        /**
         * 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountNotificationControllerGetNotifications(page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<NotificationsResponse> {
            return localVarFp.accountNotificationControllerGetNotifications(page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [notificationId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountNotificationControllerReadNotification(notificationId?: number, options?: RawAxiosRequestConfig): AxiosPromise<NotificationInfo> {
            return localVarFp.accountNotificationControllerReadNotification(notificationId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationsApi - object-oriented interface
 */
export class NotificationsApi extends BaseAPI {
    /**
     * 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountNotificationControllerGetNotifications(page?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).accountNotificationControllerGetNotifications(page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} [notificationId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountNotificationControllerReadNotification(notificationId?: number, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).accountNotificationControllerReadNotification(notificationId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * OrderApi - axios parameter creator
 */
export const OrderApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} page Page
         * @param {number} pageSize Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderControllerFetchSanitaryPadOrderHistory: async (page: number, pageSize: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            assertParamExists('orderControllerFetchSanitaryPadOrderHistory', 'page', page)
            // verify required parameter 'pageSize' is not null or undefined
            assertParamExists('orderControllerFetchSanitaryPadOrderHistory', 'pageSize', pageSize)
            const localVarPath = `/v1/account/order/sanitary-pad/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {OrderSanitaryPadDTO} orderSanitaryPadDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderControllerOrderSanitaryPad: async (orderSanitaryPadDTO: OrderSanitaryPadDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderSanitaryPadDTO' is not null or undefined
            assertParamExists('orderControllerOrderSanitaryPad', 'orderSanitaryPadDTO', orderSanitaryPadDTO)
            const localVarPath = `/v1/account/order/sanitary-pad/new`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(orderSanitaryPadDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrderApi - functional programming interface
 */
export const OrderApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrderApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} page Page
         * @param {number} pageSize Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderControllerFetchSanitaryPadOrderHistory(page: number, pageSize: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrderHistoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderControllerFetchSanitaryPadOrderHistory(page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrderApi.orderControllerFetchSanitaryPadOrderHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {OrderSanitaryPadDTO} orderSanitaryPadDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orderControllerOrderSanitaryPad(orderSanitaryPadDTO: OrderSanitaryPadDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrderInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orderControllerOrderSanitaryPad(orderSanitaryPadDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrderApi.orderControllerOrderSanitaryPad']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrderApi - factory interface
 */
export const OrderApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrderApiFp(configuration)
    return {
        /**
         * 
         * @param {number} page Page
         * @param {number} pageSize Page size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderControllerFetchSanitaryPadOrderHistory(page: number, pageSize: number, options?: RawAxiosRequestConfig): AxiosPromise<OrderHistoryResponse> {
            return localVarFp.orderControllerFetchSanitaryPadOrderHistory(page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrderSanitaryPadDTO} orderSanitaryPadDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orderControllerOrderSanitaryPad(orderSanitaryPadDTO: OrderSanitaryPadDTO, options?: RawAxiosRequestConfig): AxiosPromise<OrderInfo> {
            return localVarFp.orderControllerOrderSanitaryPad(orderSanitaryPadDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrderApi - object-oriented interface
 */
export class OrderApi extends BaseAPI {
    /**
     * 
     * @param {number} page Page
     * @param {number} pageSize Page size
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public orderControllerFetchSanitaryPadOrderHistory(page: number, pageSize: number, options?: RawAxiosRequestConfig) {
        return OrderApiFp(this.configuration).orderControllerFetchSanitaryPadOrderHistory(page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrderSanitaryPadDTO} orderSanitaryPadDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public orderControllerOrderSanitaryPad(orderSanitaryPadDTO: OrderSanitaryPadDTO, options?: RawAxiosRequestConfig) {
        return OrderApiFp(this.configuration).orderControllerOrderSanitaryPad(orderSanitaryPadDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProtectionApi - axios parameter creator
 */
export const ProtectionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {UpdateSocialHandlesDTO} updateSocialHandlesDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateSocialHandles: async (updateSocialHandlesDTO: UpdateSocialHandlesDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateSocialHandlesDTO' is not null or undefined
            assertParamExists('accountControllerUpdateSocialHandles', 'updateSocialHandlesDTO', updateSocialHandlesDTO)
            const localVarPath = `/v1/account/me/update-social-handles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSocialHandlesDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProtectionApi - functional programming interface
 */
export const ProtectionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProtectionApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {UpdateSocialHandlesDTO} updateSocialHandlesDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountControllerUpdateSocialHandles(updateSocialHandlesDTO: UpdateSocialHandlesDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountControllerUpdateSocialHandles(updateSocialHandlesDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProtectionApi.accountControllerUpdateSocialHandles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProtectionApi - factory interface
 */
export const ProtectionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProtectionApiFp(configuration)
    return {
        /**
         * 
         * @param {UpdateSocialHandlesDTO} updateSocialHandlesDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountControllerUpdateSocialHandles(updateSocialHandlesDTO: UpdateSocialHandlesDTO, options?: RawAxiosRequestConfig): AxiosPromise<AccountInfo> {
            return localVarFp.accountControllerUpdateSocialHandles(updateSocialHandlesDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProtectionApi - object-oriented interface
 */
export class ProtectionApi extends BaseAPI {
    /**
     * 
     * @param {UpdateSocialHandlesDTO} updateSocialHandlesDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountControllerUpdateSocialHandles(updateSocialHandlesDTO: UpdateSocialHandlesDTO, options?: RawAxiosRequestConfig) {
        return ProtectionApiFp(this.configuration).accountControllerUpdateSocialHandles(updateSocialHandlesDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SupportApi - axios parameter creator
 */
export const SupportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ContactUsDTO} contactUsDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        supportControllerContactUs: async (contactUsDTO: ContactUsDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactUsDTO' is not null or undefined
            assertParamExists('supportControllerContactUs', 'contactUsDTO', contactUsDTO)
            const localVarPath = `/v1/account/support/contact-us`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactUsDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SupportApi - functional programming interface
 */
export const SupportApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SupportApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ContactUsDTO} contactUsDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async supportControllerContactUs(contactUsDTO: ContactUsDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.supportControllerContactUs(contactUsDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SupportApi.supportControllerContactUs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SupportApi - factory interface
 */
export const SupportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SupportApiFp(configuration)
    return {
        /**
         * 
         * @param {ContactUsDTO} contactUsDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        supportControllerContactUs(contactUsDTO: ContactUsDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.supportControllerContactUs(contactUsDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SupportApi - object-oriented interface
 */
export class SupportApi extends BaseAPI {
    /**
     * 
     * @param {ContactUsDTO} contactUsDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public supportControllerContactUs(contactUsDTO: ContactUsDTO, options?: RawAxiosRequestConfig) {
        return SupportApiFp(this.configuration).supportControllerContactUs(contactUsDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UploadApi - axios parameter creator
 */
export const UploadApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Upload an file
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageUploadControllerUploadFile: async (file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/account/upload/file`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload an image with optional resizing
         * @param {ImageUploadControllerUploadImageTypeEnum} [type] 
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageUploadControllerUploadImage: async (type?: ImageUploadControllerUploadImageTypeEnum, file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/account/upload/image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UploadApi - functional programming interface
 */
export const UploadApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UploadApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Upload an file
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imageUploadControllerUploadFile(file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileUploadResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imageUploadControllerUploadFile(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UploadApi.imageUploadControllerUploadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload an image with optional resizing
         * @param {ImageUploadControllerUploadImageTypeEnum} [type] 
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async imageUploadControllerUploadImage(type?: ImageUploadControllerUploadImageTypeEnum, file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileUploadResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.imageUploadControllerUploadImage(type, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UploadApi.imageUploadControllerUploadImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UploadApi - factory interface
 */
export const UploadApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UploadApiFp(configuration)
    return {
        /**
         * 
         * @summary Upload an file
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageUploadControllerUploadFile(file?: File, options?: RawAxiosRequestConfig): AxiosPromise<FileUploadResult> {
            return localVarFp.imageUploadControllerUploadFile(file, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload an image with optional resizing
         * @param {ImageUploadControllerUploadImageTypeEnum} [type] 
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        imageUploadControllerUploadImage(type?: ImageUploadControllerUploadImageTypeEnum, file?: File, options?: RawAxiosRequestConfig): AxiosPromise<FileUploadResult> {
            return localVarFp.imageUploadControllerUploadImage(type, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UploadApi - object-oriented interface
 */
export class UploadApi extends BaseAPI {
    /**
     * 
     * @summary Upload an file
     * @param {File} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imageUploadControllerUploadFile(file?: File, options?: RawAxiosRequestConfig) {
        return UploadApiFp(this.configuration).imageUploadControllerUploadFile(file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload an image with optional resizing
     * @param {ImageUploadControllerUploadImageTypeEnum} [type] 
     * @param {File} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public imageUploadControllerUploadImage(type?: ImageUploadControllerUploadImageTypeEnum, file?: File, options?: RawAxiosRequestConfig) {
        return UploadApiFp(this.configuration).imageUploadControllerUploadImage(type, file, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ImageUploadControllerUploadImageTypeEnum = {
    Thumbnail: 'thumbnail',
    Logo: 'logo',
    ProductImage: 'product-image',
    CoverImage: 'cover-image',
    Medium: 'medium',
    Large: 'large'
} as const;
export type ImageUploadControllerUploadImageTypeEnum = typeof ImageUploadControllerUploadImageTypeEnum[keyof typeof ImageUploadControllerUploadImageTypeEnum];


